export const events = [
  {
    id: 'jazz-cats',
    date: '28 maart \'26',
    slug: '28.03.26',
    name: 'Jazz Cats Festival',
    venue: 'De Kreun & Muziekcentrum Track',
    color: 'black' as const,
    poster: false,
    posterText: undefined as string | undefined,
    description: 'Een dag vol jazz in al zijn vormen. Van klassiek tot avant-garde, van bebop tot fusion. Jazz Cats brengt de beste jazzmuzikanten samen op twee podia.',
    prices: [
      { label: 'Dagticket', amount: '€ 22' },
      { label: 'Wild Card (vvk)', amount: '€ 18' },
      { label: '4x4 Kaart', amount: '€ 18' },
      { label: '12-18 jaar of Studentenkaart', amount: '€ 14' },
      { label: 'Uitpas', amount: '€ 5' },
    ],
  },
  {
    id: 'dotan',
    date: '27.06.26',
    slug: '27.06.26',
    name: 'Dotan',
    venue: 'De Kreun',
    color: 'blue' as const,
    poster: false,
    posterText: undefined as string | undefined,
    description: 'Dotan brengt zijn soulvolle folk-pop naar De Kreun. Met zijn warme stem en eerlijke teksten weet hij het publiek altijd te raken.',
    prices: [
      { label: 'Voorverkoop', amount: '€ 24' },
      { label: 'Wild Card (vvk)', amount: '€ 20' },
      { label: 'Uitpas', amount: '€ 5' },
    ],
  },
  {
    id: 'terry-riley',
    date: '28.06.26',
    slug: '28.06.26',
    name: 'Terry Riley: In C / G.A.M.E. & Ensemble 0',
    venue: 'Muziekcentrum Track',
    color: 'lime' as const,
    poster: false,
    posterText: undefined as string | undefined,
    description: 'Een monumentale uitvoering van Terry Riley\'s meesterwerk "In C" door het gerenommeerde Ensemble 0. Minimalistisch en meeslepend.',
    prices: [
      { label: 'Voorverkoop', amount: '€ 19' },
      { label: 'Wild Card (vvk)', amount: '€ 15' },
      { label: 'Uitpas', amount: '€ 5' },
    ],
  },
  {
    id: 'buffalo-tom',
    date: '14.10.26',
    slug: '14.10.26',
    name: 'Buffalo Tom',
    venue: 'De Kreun',
    color: 'black' as const,
    poster: false,
    posterText: undefined as string | undefined,
    description: 'De legendarische Bostoniaanse alternatieve rockband keert terug naar Europa. Verwacht krachtige gitaren en emotionele anthems.',
    prices: [
      { label: 'Voorverkoop', amount: '€ 26' },
      { label: 'Wild Card (vvk)', amount: '€ 22' },
      { label: 'Uitpas', amount: '€ 5' },
    ],
  },
  {
    id: 'girls-go-wild',
    date: '24.04.26',
    slug: '24.04.26',
    name: 'Girls Go Wild: Rosie Stuart + TJE + Toya K',
    venue: 'De Kreun',
    color: 'pink' as const,
    poster: true,
    posterText: 'Girls Go Wild★',
    description: 'Girls Go Wild is het festival van The Young Curators — een avond vol krachtige vrouwelijke artiesten. Verwacht energie, diversiteit en onvergetelijke muziek.',
    prices: [
      { label: 'Voorverkoop', amount: '€ 17' },
      { label: 'Wild Card (vvk)', amount: '€ 14' },
      { label: '4x4 Kaart', amount: '€ 14' },
      { label: '12-18 jaar of Studentenkaart', amount: '€ 14' },
      { label: 'Uitpas', amount: '€ 5' },
    ],
  },
]
